@startuml
'https://plantuml.com/class-diagram

abstract class Person {
    id
    name
    email
    phone
}
class Borrower {
    position
}
class Author

class Book {
    id
    title
    category
    available
}


class Loan {
    id
    borrowerId
    bookId
    timeBorrow
    timeReturn
}

class Limit {
    position
    length
    number
}

class Librarian {
    librarianId
    username
    password
    name
}

Person <|-r- Borrower
Person <|-l- Author

Author }|--|{ Book

Loan }|-u-|| Borrower
Loan }|-l-|| Book

Borrower }|-|| Limit

@enduml