@startuml
'https://plantuml.com/class-diagram

abstract class Person {
    personId
    name
    email
    phone
}
class Borrower {
    position
}
class BorrowerManagement {
    list()
    search()
    add()
    delete()
    update()
}
class Author
class AuthorManagement {
    list()
    search()
    add()
    delete()
    update()
}

class Book {
    bookId
    title
    category
    status
}
class BookManagement {
    list()
    search()
    add()
    delete()
    update()
}


class Loan {
    loanId
    borrowerId
    bookId
    timeBorrow
    timeReturn
}
class LoanManagement {
    list()
    search()
    add()
    delete()
    update()
}

class Limit {
    position
    length
    number
}

class Librarian {
    librarianId
    username
    password
    name
}

Person <|-r- Borrower
Person <|-l- Author

Author }|--|{ Book

Loan }|-u-|| Borrower
Loan }|-l-|| Book

Borrower }|-|| Limit

BorrowerManagement ||-d-|{ Borrower
AuthorManagement ||-d-|{ Author
BookManagement ||-r-|{ Book
LoanManagement ||-l-|{ Loan

@enduml