@startuml
'https://plantuml.com/use-case-diagram
left to right direction
skinparam actorStyle awesome

:Thủ thư: as User

User --> (Thêm tài liệu)
User --> (Sửa thông tin tài liệu)
User --> (Xóa tài liệu)
User --> (Tìm tài liệu)
@enduml