@startuml
'https://plantuml.com/use-case-diagram
left to right direction
skinparam actorStyle awesome

:Thủ thư: as User

User --> (Thêm độc giả)
User --> (Sửa thông tin độc gia)
User --> (Xóa độc giả)
User --> (Tìm độc giả)
@enduml